[tool.black]
line-length = 100
skip-magic-trailing-comma = true
include = '\.py$'
exclude = '''
/(
    README\.md
    | dump\.rdb
    | requirements\.txt
    | start_services\.sh
    | pyproject\.toml
)$
'''
